[[getting-started]]
= Getting started =

== Overview ==

* == monitoring tool /
    ** goal
        *** visualize information / -- provided by -- Spring Boot Actuators
    ** == server + client
        *** server == UI /
            **** -- displays & interacts with -- Spring Boot Actuators
            **** 👁️-- can run as -- 👁️
                ***** servlet application or
                ***** webflux application
        *** client / register | server & access actuator endpoints

[[set-up-admin-server]]
== Quick Start ==

* set up a Spring Boot application
    ** Reason: 🧠 Spring Boot Admin -- relies on -- Spring Boot 🧠
    ** use http://start.spring.io
        *** add the proper Spring Boot Starter
            **** _Example:_ use servlet web starter

+
[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>spring-boot-admin-starter-server</artifactId>
    <version>{project-version}</version>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
</dependency>
----

+
[source,java]
----
@SpringBootApplication
@EnableAdminServer
public class SpringBootAdminApplication {
    public static void main(String[] args) {
        SpringApplication.run(SpringBootAdminApplication.class, args);
    }
}
----

* if you want to set up the Spring Boot Admin Server -- via -- war-deployment | servlet-container -> check {github-src}/spring-boot-admin-samples/spring-boot-admin-sample-war/[spring-boot-admin-sample-war]
* if you want to add security -> check  {github-src}/spring-boot-admin-samples/spring-boot-admin-sample-servlet/[spring-boot-admin-sample-servlet]

[[register-client-applications]]
== Registering Client Applications ==

* ways to register your application | SBA Server
    ** include the SBA Client or
    ** use https://spring.io/projects/spring-cloud[Spring Cloud Discovery]
        *** _Example:_ Eureka, Consul, ...
        *** <<server#spring-cloud-discovery-static-config, option using a static configuration | SBA Server side>>

[[register-clients-via-spring-boot-admin]]
=== Spring Boot Admin Client ===

* _Example:_

+
[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>spring-boot-admin-starter-client</artifactId>
    <version>{project-version}</version>
</dependency>

<!-- if you want to secure the endpoints -->
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
</dependency>
----

+
[source]
.application.properties
----
// spring.boot.admin.client.url=SpringBootAdminServerURL
spring.boot.admin.client.url=http://localhost:8080

// From Spring Boot v2 -> MOST of the endpoints are NOT exposed via http
management.endpoints.web.exposure.include=*  // expose ALL -- NOT recommended | production
management.info.env.enabled=true             // by default, it's disabled
----

+
[source,java]
----
@Configuration
public static class SecurityPermitAllConfig {
    @Bean
    protected SecurityFilterChain filterChain(HttpSecurity http) {
        return http.authorizeHttpRequests((authorizeRequests) -> authorizeRequests.anyRequest().permitAll())        // enable ALL -> also the actuator endpoints
            .csrf().disable().build();
    }
}
----


[[discover-clients-via-spring-cloud-discovery]]
=== Spring Cloud Discovery ===

* TODO:
If you already use Spring Cloud Discovery for your applications you don't need the SBA Client. Just add a DiscoveryClient to Spring Boot Admin Server, the rest is done by our AutoConfiguration.

The following steps uses Eureka, but other Spring Cloud Discovery implementations are supported as well. There are examples using {github-src}/spring-boot-admin-samples/spring-boot-admin-sample-consul/[Consul] and https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-zookeeper/[Zookeeper].

Also, have a look at the http://projects.spring.io/spring-cloud/spring-cloud.html[Spring Cloud documentation].

. Add spring-cloud-starter-eureka to your dependencies:
+
[source,xml]
.pom.xml
----
include::{samples-dir}/spring-boot-admin-sample-eureka/pom.xml[tags=dependency-eureka,indent=0]
----

. Enable discovery by adding `@EnableDiscoveryClient` to your configuration:
+
[source,java]
----
@Configuration
@EnableAutoConfiguration
@EnableDiscoveryClient
@EnableScheduling
@EnableAdminServer
public class SpringBootAdminApplication {
    public static void main(String[] args) {
        SpringApplication.run(SpringBootAdminApplication.class, args);
    }
}
----

. Tell the Eureka client where to find the service registry:
+
[source,yml]
.application.yml
----
include::{samples-dir}/spring-boot-admin-sample-eureka/src/main/resources/application.yml[tags=configuration-eureka]
----
<1> Configuration section for the Eureka client
<2> As with Spring Boot 2 most of the endpoints aren't exposed via http by default, we expose all of them. For production you should carefully choose which endpoints to expose.

See also {github-src}/spring-boot-admin-samples/spring-boot-admin-sample-eureka/[spring-boot-admin-sample-eureka].

TIP: You can include the Spring Boot Admin Server to your Eureka server. Setup everything as described above and set `spring.boot.admin.context-path` to something different than `"/"` so that the Spring Boot Admin Server UI won't clash with Eureka's one.

== Use of SNAPSHOT-Versions ==

* if you want to use a snapshot version of Spring Boot Admin Server -> add

[source,xml]
.pom.xml
----
<repositories>
    <repository>
        <id>spring-milestone</id>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
        <url>http://repo.spring.io/milestone</url>
    </repository>
    <repository>
        <id>spring-snapshot</id>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
        <url>http://repo.spring.io/snapshot</url>
    </repository>
    <repository>
        <id>sonatype-nexus-snapshots</id>
        <name>Sonatype Nexus Snapshots</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
        <releases>
            <enabled>false</enabled>
        </releases>
    </repository>
</repositories>
----
